const path = require('path'),
  { EventEmitter } = require('events'),
  fs = require('fs'),
  minify = require('html-minifier').minify,
  logger = require('debug')('JSENGINE:main'),
  util = require('util'),
  memoize = require('fast-memoize'),
  write = util.promisify(fs.writeFile),
  View = require('./view'),
  helpers = require('./helpers');

logger.log = console.log.bind(console);
logger.error = console.error.bind(console);


const getMinifyOptions = (dev) => ({
  collapseBooleanAttributes: true,
  collapseInlineTagWhitespace: true,
  collapseWhitespace: !dev,
  includeAutoGeneratedTags: !dev,
  removeComments: !dev,
  removeOptionalTags: !dev,
  removeEmptyAttributes: !dev,
  removeRedundantAttributes: !dev
});

class JsEngine extends EventEmitter {
  constructor(opts) {
    super()
    const isDevelopment = process.env.NODE_ENV === 'development';

    this.options = Object.assign({
      assets: '/assets',
      isDevelopment: isDevelopment,
      cache: !isDevelopment,
      minify: true,
      printComments: isDevelopment,
      helpers: helpers,
      formatLang: { lang: 'pt-BR', currency: 'BRL' },
      views: path.join(path.dirname(process.mainModule.filename), 'views')
    }, opts);

    this.__express = this.render.bind(this);
    this.__cachedRender = memoize(this.render).bind(this);
    logger('JsEngine instance created with options: %O ', this.options)
  }

  render(moduleOrFullPath, model, callback) {
    logger('Start rendering: ' + moduleOrFullPath);
    this.emit('render', { moduleOrFullPath, model })

    let html = '',
      error = undefined;

    const hrstart = process.hrtime();

    try {
      const view = new View(moduleOrFullPath, model, 'view', this.options);
      html = view.execute();

      if (this.options.minify) {
        html = Object.freeze(minify(html, getMinifyOptions(this.options.isDevelopment)));
      }
    } catch (e) {
      logger(e);
      error = e;
    }
    finally {
      const hrend = process.hrtime(hrstart);
      const end = util.format('Execution time (hr): %ds %dms', hrend[0], hrend[1] / 1000000);
      logger('End rendering [%s] %s', moduleOrFullPath, end);
      this.emit('rendered', { end, html, error })
      if (typeof callback === "function") return callback(error, html);
      return error ? error : html;
    }
  }
}

module.exports = JsEngine;