const path = require('path'),
  fs = require('fs'),
  minify = require('html-minifier').minify,
  logger = require('debug')('JSENGINE:main'),
  util = require('util'),
  write = util.promisify(fs.writeFile),
  View = require('./view'),
  helpers = require('./helpers');


const getMinifyOptions = (dev) => ({
  collapseBooleanAttributes: true,
  collapseInlineTagWhitespace: true,
  collapseWhitespace: !dev,
  includeAutoGeneratedTags: !dev,
  removeComments: !dev,
  removeOptionalTags: !dev,
  removeEmptyAttributes: !dev,
  removeRedundantAttributes: !dev
});

class JsEngine {
  constructor(opts) {
    const isDevelopment = process.env.NODE_ENV === 'development';

    this.options = Object.assign({
      isDevelopment: isDevelopment,
      cache: !isDevelopment,
      minify: !isDevelopment,
      printComments: isDevelopment,
      helpers: helpers,
      formatLang: { lang: 'pt-BR', currency: 'BRL' },
      views: path.join(path.dirname(process.mainModule.filename), 'views')
    }, opts);

    this.__express = this.render.bind(this);
  }

  render(fullPath, model, callback) {
    logger('Start rendering: ' + fullPath);
    console.time(fullPath);
    try {
      const view = new View(fullPath, model, 'view', this.options);
      let html = view.execute();


      if (this.options.minify) {
        html = minify(html, getMinifyOptions(this.options.isDevelopment));
      }

      return callback(null, html);
    } catch (error) {
      logger(error);
      return callback(error);
    }
    finally {
      console.timeEnd(fullPath);
    }
  }
}

module.exports = JsEngine;
